@startuml

!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include c4/C4_Container.puml
!include FONTAWESOME/users.puml

title CinemaAbyss Container Diagram

AddRelTag(tvApi, $textColor="#31718F", $lineColor="#31718F")
AddRelTag(mobileApi, $textColor="#964435", $lineColor="#964435")
AddRelTag(webApi, $textColor="#8F756F", $lineColor="#8F756F")
AddRelTag(wsApi, $textColor="#1DC2B7", $lineColor="#1DC2B7")
AddRelTag(messagingConsumer, $textColor="#348018", $lineColor="#348018", $lineStyle = DashedLine())
AddRelTag(messagingProducer, $textColor="#D41E1E", $lineColor="#D41E1E", $lineStyle = DashedLine())
AddElementTag(tv, $bgColor="#31718F", $fontColor="white", $borderColor="#31718F")
AddElementTag(mobile, $bgColor="#964435", $fontColor="white", $borderColor="#964435")
AddElementTag(web, $bgColor="#8F756F", $fontColor="white", $borderColor="#8F756F")
AddElementTag(ws, $bgColor="#1DC2B7", $fontColor="white", $borderColor="#1DC2B7")
AddElementTag(db, $bgColor="#763596", $fontColor="white", $borderColor="white", $shadowing="true", $shape = RoundedBoxShape())
AddElementTag(nosql, $bgColor="#C21D99", $fontColor="white", $borderColor="white", $shadowing="true", $shape = RoundedBoxShape())

Person(user, "Users", "Users of the CinemaAbyss system", $sprite="users")
System(CinemaAbyssSystem, "CinemaAbyss System", "Cinema streaming system")

System_Boundary(CinemaAbyssSystem, "CinemaAbyss System") {
  Container(Frontend, "Web Interface", "JavaScript, React", $tags=web)
  Container(Mobile, "Mobile Application", "Kotlin, Swift", $tags=mobile)
  Container(SmartTV, "Smart TV", "Kotlin", $tags=tv)

  Container(BFF_WEB, "BFF Frontend", "Java, Spring", $tags=web)
  Container(BFF_Mobile, "BFF Mobile", "Java, Spring", $tags=mobile)
  Container(BFF_TV, "BFF Smart TV", "Java, Spring", $tags=tv)
  Container(WS, "Websocket service", "Java, Spring", $tags=ws)

  Container(AuthSrv, "Auth Service", "Java, Spring")
  Container(UserSrv, "User service", "Java, Spring")

  Container(PaymentSrv, "Payment service", "Java, Spring")
  Container(MoviesSrv, "Movies service", "Java, Spring")
  Container(EventsSrv, "Events service", "Java, Spring")
  Container(SubscriptionSrv, "Subscription service", "Java, Spring")

  ContainerDb(DB, "Database", "Кластер PostgreSQL", $tags=db) {
    Container(DBNode1, "Node", $tags=db)
    Container(DBNode2, "Node", $tags=db)
    Container(DBNode3, "Node", $tags=db)
  }
  ContainerDb(Cassandra, "NoSQL Database", "Кластер Cassandra", $tags=nosql) {
      Container(CasNode1, "Node", $tags=nosql)
      Container(CasNode2, "Node", $tags=nosql)
      Container(CasNode3, "Node", $tags=nosql)
    }
  Container_Boundary(Broker, "Message broker (Кластер Kafka)") {
    Container(BrNode1, "Node")
    Container(BrNode2, "Node")
    Container(BrNode3, "Node")
  }
  Container(Keycloak, "Auth provider", "Keycloak")
  Container(S3, "File storage", "S3")
}

System_Ext(MovieExt, "Кинопоиск", "Кино-контент")
System_Ext(MovieExt2, "Okko", "Кино-контент")
System_Ext(MovieExt3, "КИОН", "Кино-контент")
System_Ext(MovieExt4, "Netflix", "Кино-контент")
System_Ext(LoyaltySrv, "Яндекс Плюс", "Сервис лояльности")
System_Ext(LoyaltySrv2, "Сбер Прайм", "Сервис лояльности")
System_Ext(LoyaltySrv3, "МТС Подписка", "Сервис лояльности")
System_Ext(BankExt, "Bank system", "Банковские системы")

Rel_D(user, Frontend, "Uses system")
Rel_D(user, Mobile, "Uses system")
Rel_D(user, SmartTV, "Uses system")
Rel_D(Frontend, BFF_WEB, "REST API", "HTTP/HTTPS", $tags=webApi)
Rel_D(Frontend, BFF_WEB, "Get movies", "MPEG-DASH/HLS", $tags=webApi)
Rel_D(Mobile, BFF_Mobile, "GraphQL API", "HTTP/HTTPS", $tags=mobileApi)
Rel_D(Mobile, BFF_Mobile, "Get movies", "MPEG-DASH/HLS", $tags=mobileApi)
Rel_D(SmartTV, BFF_TV, "Get movies", "MPEG-DASH/HLS", $tags=tvApi)
Rel_D(SmartTV, BFF_TV, "REST API", "HTTP/HTTPS", $tags=tvApi)
Rel_U(WS, Frontend, "Notifications", "Websocket", $tags=wsApi)
Rel_U(WS, Mobile, "Notifications", "Websocket", $tags=wsApi)
Rel_U(WS, SmartTV, "Notifications", "Websocket", $tags=wsApi)
Rel_D(BFF_WEB, AuthSrv, "Authentication", "HTTP/HTTPS", $tags=webApi)
Rel_D(BFF_Mobile, AuthSrv, "Authentication", "HTTP/HTTPS", $tags=mobileApi)
Rel_D(BFF_TV, AuthSrv, "Authentication", "HTTP/HTTPS", $tags=tvApi)
Rel_L(AuthSrv, Keycloak, "Auth", "HTTP/HTTPS")
Rel_D(BFF_WEB, SubscriptionSrv, "Get/Buy subscriptions", "HTTP/HTTPS", $tags=webApi)
Rel_D(BFF_Mobile, SubscriptionSrv, "Get/Buy subscriptions", "HTTP/HTTPS", $tags=mobileApi)
Rel_D(BFF_TV, SubscriptionSrv, "Get/Buy subscriptions", "HTTP/HTTPS", $tags=tvApi)
Rel_L(SubscriptionSrv, PaymentSrv, "Buy subscriptions", "HTTP/HTTPS")
Rel_D(PaymentSrv, BankExt, "Buy subscriptions", "HTTP/HTTPS")
Rel_L(SubscriptionSrv, UserSrv, "Save/Get subscriptions metadata", "HTTP/HTTPS")
Rel(SubscriptionSrv, Broker, "Pull subscriptions", "Kafka", $tags=messagingConsumer)
Rel_L(UserSrv, DB, "Save/Get user and related domains info", "SQL")
Rel_U(LoyaltySrv, Broker, "Push subscriptions", "Kafka", $tags=messagingProducer)
Rel_U(LoyaltySrv2, Broker, "Push subscriptions", "Kafka", $tags=messagingProducer)
Rel_U(LoyaltySrv3, Broker, "Push subscriptions", "Kafka", $tags=messagingProducer)
Rel_U(MovieExt, Broker, "Push movies", "Kafka", $tags=messagingProducer)
Rel_U(MovieExt2, Broker, "Push movies", "Kafka", $tags=messagingProducer)
Rel_U(MovieExt3, Broker, "Push movies", "Kafka", $tags=messagingProducer)
Rel_U(MovieExt4, Broker, "Push movies", "Kafka", $tags=messagingProducer)
Rel(MoviesSrv, Broker, "Pull movies", "Kafka", $tags=messagingConsumer)
Rel_L(MoviesSrv, SubscriptionSrv, "Check subscriptions")
Rel_U(MoviesSrv, S3, "Save/Get movies")
Rel_L(MoviesSrv, UserSrv, "Save/Get movies metadata", "HTTP/HTTPS")
Rel_D(BFF_WEB, MoviesSrv, "Get movies", "HTTP/HTTPS", $tags=webApi)
Rel_D(BFF_Mobile, MoviesSrv, "Get movies", "HTTP/HTTPS", $tags=mobileApi)
Rel_D(BFF_TV, MoviesSrv, "Get movies", "HTTP/HTTPS", $tags=tvApi)
Rel_U(EventsSrv, WS, "Send events data", "Websocket", $tags=wsApi)
Rel_D(SubscriptionSrv, Broker, "Push events data", "Kafka", $tags=messagingProducer)
Rel_D(PaymentSrv, Broker, "Push events data", "Kafka", $tags=messagingProducer)
Rel_D(MoviesSrv, Broker, "Push events data", "Kafka", $tags=messagingProducer)
Rel_D(UserSrv, Broker, "Push events data", "Kafka", $tags=messagingProducer)
Rel_D(EventsSrv, Broker, "Pull events data", "Kafka", $tags=messagingConsumer)
Rel_D(EventsSrv, Cassandra, "Save events data", "SQL")

Lay_R(Frontend, Mobile)
Lay_R(Mobile, SmartTV)
Lay_U(BFF_WEB, Frontend)
Lay_U(BFF_TV, SmartTV)
Lay_U(BFF_Mobile, Mobile)
Lay_U(WS, Mobile)
Lay_U(WS, SmartTV)
Lay_U(WS, Frontend)
Lay_R(WS, BFF_TV)
Lay_U(AuthSrv,BFF_WEB)
Lay_R(UserSrv,SubscriptionSrv)
Lay_U(PaymentSrv,AuthSrv)
Lay_R(MoviesSrv,PaymentSrv)
Lay_U(MoviesSrv,AuthSrv)
Lay_U(EventsSrv,AuthSrv)
Lay_U(SubscriptionSrv, AuthSrv)
Lay_R(EventsSrv, MoviesSrv)
Lay_R(Keycloak,AuthSrv)
Lay_U(Broker,MoviesSrv)
Lay_U(DB,UserSrv)
Lay_U(Cassandra,EventsSrv)
Lay_U(S3,MoviesSrv)
Lay_R(BrNode1,BrNode2)
Lay_R(DBNode1,DBNode2)
Lay_R(CasNode1,CasNode2)

Lay_U(MovieExt,Broker)
Lay_U(MovieExt2,Broker)
Lay_U(MovieExt3,Broker)
Lay_U(MovieExt4,Broker)
Lay_D(BankExt,PaymentSrv)
Lay_U(LoyaltySrv,MovieExt2)
Lay_U(LoyaltySrv2,MovieExt2)
Lay_U(LoyaltySrv3,MovieExt2)

SHOW_LEGEND()
@enduml